### ISSUE TITLE
Expose a way to add functions to the FluentBundle

### ISSUE THREAD

**Issue by tobyzerner** [jrmajor/laravel-fluent#3]
Currently the `FluentBundle` instances created inside the `FluentTranslator` class cannot be configured after construction, so it's impossible to call `addFunction`.

Perhaps a method could be added to `FluentTranslator` to allow adding functions when new bundles are constructed? Something like:

```php
$translator = app('translator'); // instanceof FluentTranslator

$translator->addFunction('MY_FUNCTION', Closure::fromCallable('my_function'));
```

Then the FluentTranslator would pass these on whenever a bundle is created.

The user would call this in their own service provider. I don't think config files are useful here as they [cannot contain closures](https://github.com/laravel/framework/issues/9625).

**Comment by jrmajor** [comment]
Thank you for the suggestion, that would be a useful addition. I will add it tomorrow.
